version: '2'
services:
  http-receiver-1:
    image: ubirch/${project.artifactId}:${build.number}
    depends_on:
    - kafka
    - zookeeper
    ports:
    - "8080:8080"
    - "9010:9010"
    - "2552"
    hostname: "http-receiver-1"
    environment:
      KAFKA_URL: "kafka:9092"
      KAFKA_TOPIC_REQUEST_PAYLOAD_BIN: "request.payload.bin"
      KAFKA_TOPIC_RESPONSE_PAYLOAD_BIN: "response.payload.bin"
      AKKA_CLUSTER_NODE_NAME: "http-receiver-1"
      CLUSTER_SEED_NODES : "akka.tcp://http-receiver@http-receiver-1:2552,akka.tcp://http-receiver@http-receiver-2:2552"
  http-receiver-2:
    image: ubirch/${project.artifactId}:${build.number}
    depends_on:
    - kafka
    - zookeeper
    ports:
    - "8081:8080"
    - "9011:9010"
    - "2552"
    hostname: "http-receiver-2"
    environment:
      KAFKA_URL: "kafka:9092"
      KAFKA_TOPIC_REQUEST_PAYLOAD_BIN: "request.payload.bin"
      KAFKA_TOPIC_RESPONSE_PAYLOAD_BIN: "response.payload.bin"
      AKKA_CLUSTER_NODE_NAME: "http-receiver-2"
      CLUSTER_SEED_NODES : "akka.tcp://http-receiver@http-receiver-1:2552,akka.tcp://http-receiver@http-receiver-2:2552"
