{{- define "niomon-http.env" -}}
- name: DEPLOYMENT_MODE
  value: "cluster"
- name: HTTP_PORT
  value: "8080"
- name: KAFKA_TOPIC_OUT
  value: "binary.request"
- name: KAFKA_TOPIC_IN
  value: "binary.response"
- name: K8S_NAMESPACE
  value: "{{ .Values.namespace }}"
- name: HOSTNAME
  valueFrom:
   fieldRef:
    apiVersion: v1
    fieldPath: status.podIP
{{- end -}}

{{- $deployment := (dict "envStr" (include "niomon-http.env" .)) -}}

{{- $_ := set $deployment "Root" . -}}
{{- $_ := set $deployment "name" "http" -}}
{{- $_ := set $deployment "readinessPort" 8080 -}}
{{- $_ := set $deployment "replicas" 3 -}}
{{- $_ := set $deployment "ports" (tuple (dict "name" "akka-management" "port" 8558) (dict "name" "akka-remoting" "port" 2551)) -}}
{{- $_ := set $deployment "serviceAccountName" "ingest" -}}

{{- define "niomon-http.servicePorts" -}}
- name: http
  port: 8080
  protocol: TCP
- name: java-debug
  port: 9020
  protocol: TCP
  nodePort: 30020
- name: akka-management
  port: 8558
  protocol: TCP
{{- end -}}

{{- $_ := set $deployment "servicePorts" (include "niomon-http.servicePorts" .)}}

{{ template "niomon.deployment" $deployment }}

---

{{ template "niomon.service" $deployment }}

---

{{ template "niomon.prometheus.monitor" $deployment}}
