{
 "title": "Niomon Http",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Default Required Contact Points",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(akka_cluster_configured_req_contact_pts)",
     "legendFormat": "Default Req Contact Points"
    }
   ]
  },
  {
   "title": "Leaders",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(akka_cluster_is_leader)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Cluster Size Avg",
   "type": "singlestat",
   "description": "Cluster size -it includes leader-",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(akka_cluster_members)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Cluster Leaders Reported",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "akka_cluster_leader ", "legendFormat": "{{instance}}-{{pod}}" }
   ]
  },
  {
   "title": "Cluster Members Unreachable Reported",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "akka", "legendFormat": "{{instance}}-{{pod}}" }
   ]
  },
  {
   "title": "Cluster Members Reported",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "akka_cluster_members", "legendFormat": "{{instance}}-{{pod}}" }
   ]
  },
  {
   "title": "Cluster Members Reported",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "avg(akka_cluster_members)", "legendFormat": "{{instance}}-{{pod}}" }
   ]
  },
  {
   "title": "Cluster Members Role Reported",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "akka_cluster_is_leader ", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Cluster Members Role Reported (Bars)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Leader" }
   ],
   "targets": [
    { "expr": "akka_cluster_is_leader", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}