apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingest
  namespace: {{ .Values.namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingest
subjects:
- kind: ServiceAccount
  name: ingest
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: ingest
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingest
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - ingest
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: ingest
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65536
    min: 1
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - IPC_LOCK
  - SYS_RESOURCE
